# This is a basic workflow to help you get started with Actions

name: Deploy to EC2

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Logs into AWS ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push the Docker image to ECR
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pa_hotel_ai_assistant
          IMAGE_TAG: latest
        run: |
          # Check if repository exists, create if it doesn't
          aws ecr describe-repositories --repository-names $ECR_REPOSITORY --region us-east-2 || aws ecr create-repository --repository-name $ECR_REPOSITORY --region us-east-2

          # Build and push the image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # SSH into the EC2 instance and run the Docker container
      - name: SSH into EC2, configure NGINX with SSL, and run Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and install nginx
            sudo apt-get update
            sudo apt-get install -y nginx
  
            # Save SSL certificate and private key
            echo "${{ secrets.SSL_CRT }}" | sudo tee /etc/ssl/certs/princealbergrawler.crt > /dev/null
            echo "${{ secrets.SSL_KEY }}" | sudo tee /etc/ssl/private/princealbergrawler.key > /dev/null
  
            # Create nginx config for HTTPS
            sudo tee /etc/nginx/sites-available/princealbergrawler.dblytics.com > /dev/null <<EOF
            server {
                listen 80;
                server_name princealbergrawler.dblytics.com;
                return 301 https://\$host\$request_uri;
            }
  
            server {
                listen 443 ssl;
                server_name princealbergrawler.dblytics.com;
  
                ssl_certificate /etc/ssl/certs/princealbergrawler.crt;
                ssl_certificate_key /etc/ssl/private/princealbergrawler.key;
  
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_ciphers HIGH:!aNULL:!MD5;
  
                location / {
                    proxy_pass http://localhost:5000;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade \$http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host \$host;
                    proxy_cache_bypass \$http_upgrade;
                }
            }
            EOF
  
            # Enable site and disable default
            sudo ln -sf /etc/nginx/sites-available/princealbergrawler.dblytics.com /etc/nginx/sites-enabled/
            sudo rm -f /etc/nginx/sites-enabled/default || true
  
            # Test and reload nginx
            sudo nginx -t && sudo systemctl reload nginx
  
            # Login to AWS ECR
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 664418994345.dkr.ecr.us-east-2.amazonaws.com
  
            # Stop and remove existing container
            docker stop pa_hotel_ai_assistant-container || true
            docker rm pa_hotel_ai_assistant-container || true
  
            # Run the container
            docker run -d --name pa_hotel_ai_assistant-container \
              -p 5000:5000 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
              -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
              -e SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} \
              -e SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} \
              -e N8N_WEBHOOK_URL=${{ secrets.N8N_WEBHOOK_URL }} \
              -e HOST=0.0.0.0 \
              --restart unless-stopped \
              ${{ steps.build-image.outputs.image }}
  